### PR TITLE
[JENKINS-65161] remove commons-digester2 from core and upgrade plugins to commons-digester3

### PR DESCRIPTION
**Pull request by olamy**

### CODE REVIEW

**Comment by olamy** [comment]
see https://github.com/jenkinsci/jenkins/pull/5320

**Review by alecharp — APPROVED** [review]

**Review by MRamonLeon — APPROVED** [review]

**Comment by alecharp** [comment]
@atombrella do you think could merge this PR and cut a release of the plugin? Thanks.

**Review by jtnord — APPROVED** [review]

**Review by atombrella — APPROVED** [review]

**Comment by atombrella** [comment]
@alecharp Yes, I'll create a release later today.

**Comment by MRamonLeon** [comment]
could you act on this as well @atombrella? https://github.com/jenkinsci/clearcase-ucm-plugin/pull/5 Although this one needs some artifacts to become available again somewhere

**Pull request merged**
